COMPS-ENVIRONMENT-SUMMARY-1:
  Desc: I can display summary about comps environment groups
  Then:
  - Number of available comps environment groups MUST be displayed
  - Number of installed comps environment groups MUST be displayed
