COMPS-ENVIRONMENT-INSTALL-1:
  Desc: I can install RPMs from comps groups in a comps environment group
  Then:
  - Group MUST be installed [COMPS-GROUP-INSTALL-1]
  - Environment MUST be marked as installed in the Software Database.
COMPS-ENVIRONMENT-INFO-2:
  Desc: I can install RPMs from comps groups in a comps environment by $grpspec
  Where:
    COMPS-ENVIRONMENT-INSTALL-2.1: $grpspec is environment ID
    COMPS-ENVIRONMENT-INSTALL-2.2: $grpspec is environment Name
    COMPS-ENVIRONMENT-INSTALL-2.3: $grpspec is translated environment Name
    COMPS-ENVIRONMENT-INSTALL-2.4: $pkgspec contains wildcards
  Then:
  - Environment MUST be installed [COMPS-ENVIRONMENT-INSTALL-1]
