COMPS-ENVIRONMENT-MARK-REMOVE-1:
  Desc: I can mark a comps environment as removed
  Then:
  - The environment MUST be marked as removed in the Software Database.
COMPS-ENVIRONMENT-MARK-REMOVE-2:
  Desc: I can mark a comps environment as installed by $grpspec
  Where:
    COMPS-ENVIRONMENT-MARK-REMOVE-2.1: $grpspec is environment ID
    COMPS-ENVIRONMENT-MARK-REMOVE-2.2: $grpspec is environment Name
    COMPS-ENVIRONMENT-MARK-REMOVE-2.3: $grpspec is translated environment Name
    COMPS-ENVIRONMENT-MARK-REMOVE-2.4: $pkgspec contains wildcards
  Then:
  - The environment MUST be marked as removed [COMPS-ENVIRONMENT-MARK-REMOVE-1]
  Examples:
  - yum group mark remove developer-workstation-environment
  - yum group mark remove 'Development and Creative Workstation'
